import { IncomingMessage, ServerResponse } from 'http';
import { getSupabaseClient } from '../lib/supabase';
import { Sale } from '../types';
import { INITIAL_SALES_DATA } from '../constants';

interface CustomRequest extends IncomingMessage {
  query: {
    id?: string;
  };
  json: () => Promise<any>;
  method?: string;
  url?: string;
}

interface CustomResponse extends ServerResponse {
  json: (data: any) => void;
  setHeader(name: string, value: string | string[]): this;
  statusCode: number;
  end(cb?: () => void): this;
}

const allowCors = (fn: Function) => async (req: CustomRequest, res: CustomResponse) => {
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );
  if (req.method === 'OPTIONS') {
    res.statusCode = 200;
    res.end();
    return;
  }
  return await fn(req, res);
};

async function handler(req: CustomRequest, res: CustomResponse) {
  const supabase = getSupabaseClient();

  // Seeding logic
  const { data: countData } = await supabase.from('sales').select('id', { count: 'exact' });
  if (countData?.length === 0) {
    const { error: upsertError } = await supabase
      .from('sales')
      .upsert(INITIAL_SALES_DATA, { onConflict: 'id' }); // Assuming 'id' could be generated by the client for seeding if needed
    if (upsertError) console.error('Error seeding sales:', upsertError);
  }

  switch (req.method) {
    case 'GET': {
      const { data, error } = await supabase.from('sales').select('*');
      if (error) {
        res.statusCode = 500;
        res.json({ message: 'Error fetching sales', error: error.message });
        return;
      }
      res.statusCode = 200;
      res.json(data);
      break;
    }

    case 'POST': {
      const newSaleData: Omit<Sale, 'id'> = await req.json();
      const { data, error } = await supabase.from('sales').insert(newSaleData).select('*').single();
      if (error) {
        res.statusCode = 500;
        res.json({ message: 'Error adding sale', error: error.message });
        return;
      }
      res.statusCode = 201;
      res.json(data);
      break;
    }

    default: {
      res.statusCode = 405;
      res.json({ message: 'Method Not Allowed' });
      break;
    }
  }
}

export default allowCors(handler);